from enum import StrEnum


class IncidentState(StrEnum):
    DETECTED = "DETECTED"
    TRIAGED = "TRIAGED"
    DIAGNOSED = "DIAGNOSED"
    PLANNED = "PLANNED"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    EXECUTING = "EXECUTING"
    VERIFYING = "VERIFYING"
    RESOLVED = "RESOLVED"
    ESCALATED = "ESCALATED"
    FAILED = "FAILED"
    ROLLEDBACK = "ROLLEDBACK"


class Severity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class RiskLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ExecutionStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    ROLLEDBACK = "ROLLEDBACK"


class EventSource(StrEnum):
    ALERTMANAGER = "ALERTMANAGER"
    GENERIC = "GENERIC"
    ISOLATION_FOREST = "ISOLATION_FOREST"
    CLOUDWATCH = "CLOUDWATCH"


class UserRole(StrEnum):
    VIEWER = "viewer"
    OPERATOR = "operator"
    APPROVER = "approver"
    ADMIN = "admin"


class RootCause(StrEnum):
    CONTAINER_STOPPED = "CONTAINER_STOPPED"
    CPU_SATURATION = "CPU_SATURATION"
    API_UNRESPONSIVE = "API_UNRESPONSIVE"
    DEPENDENCY_UNAVAILABLE = "DEPENDENCY_UNAVAILABLE"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    NO_ACTIVE_FAULT = "NO_ACTIVE_FAULT"
    AMBIGUOUS = "AMBIGUOUS"


class EvidenceKind(StrEnum):
    METRICS = "METRICS"
    LOGS = "LOGS"
    CONTAINER_STATE = "CONTAINER_STATE"
    RESOURCE_CHANGES = "RESOURCE_CHANGES"
    ALERT_EVALUATION = "ALERT_EVALUATION"
    READINESS_PROBE = "READINESS_PROBE"
